version: "3"
services:
  app:
    build: .
    command: yarn start:dev
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
      - ./app:/usr/src/app/app
    networks:
      - mongo-compose-network
      
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - 27017:27017
    volumes:
      - ./app:/usr/src/app/app
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
